# -*- coding: utf-8 -*-
"""PyPoll.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K02x8lBoiADOBDRLmPyZkPXiauRn8LNa
"""

#####Election Data Analysis######

import csv
filename="election_data.csv"
def extract_data_from_csv(filename):
    data = []
    with open(filename, 'r') as file:
        csv_reader = csv.reader(file)
        for row in csv_reader:
            data.append(row)
    return data

data = extract_data_from_csv("election_data.csv")

data

#Number of votes:
len(data)

unique_entries = list(set(sublist[2] for sublist in data))
print("List of unique entries from the second element:", unique_entries)

count_dict = {}
for entry in unique_entries:
    count_dict[entry] = sum(1 for sublist in data if sublist[2] == entry)

print("Count of associated values in Votes:")
for entry, count in count_dict.items():
    print(entry, ":", (count/len(data))*100)

#The Winner is Diana DeGette.

